### ISSUE TITLE
Sửa lại api tìm kiếm, thêm router xóa menu

### ISSUE THREAD

**Issue by haivd95** [webpress-vn/menu-manager#1]
1. ở src/app/http/Controllers/MenuController.php  function index sửa
      $q->where('title', 'like', "%{$search}%");    thành     $q->where('name', 'like', "%{$search}%"); 

2. ở src/routers.php thêm một router xóa menu
      $api->delete('menus/{id}', 'VCComponent\Laravel\Menu\Http\Controllers\Admin\Menu\MenuController@delete');

**Comment by sonhaichu** [comment]
Done #2
